apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:  
  name: mon-kafka
  namespace: monitoring
  labels:
    app: prometheus    
    prometheus: mon
spec:  
  endpoints:
  - port: jmx
    interval: 10s  
  namespaceSelector:
    matchNames:
    - kafka
  selector:
    matchLabels:
      app: monitor
